export default {
    plataforms: ["Youtube", "Twitch", "Facebook", "TikTok", "Instagram", "Discord", "Reddit", "Twitter", "LinkedIn", "Snapchat"
  ],
  nome: [
    "Zephyr Quantum",
    "Mika Sato",
    "Bjorn Steinsonsoon",
    "Lucia Romanescu",
    "Dmitri Volkov",
    "Amara Okafor",
    "Chen Wei",
    "Isabella Moretti",
    "Marcus Johannsen",
    "Yuki Tanaka",
    "Pavel Sokolov",
    "Fatima Al-Rashid",
    "Hugo Bergström",
    "Priya Sharma",
    "Kai Nakamura",
    "Elena Petrov",
    "Javier Montoya",
    "Asha Patel",
    "Reno Fischer",
    "Zara Mikhailov",
    "Akira Kimura",
    "Sofia Kovalenko",
    "Leonardo Ferreira",
    "Anaya Gupta",
    "Viktor Smirnov",
    "Leila Hassan",
    "Erik Lunnqvist",
    "Camila Santos",
    "Adrian Krawczyk",
    "Noor Farah"
  ],
  frases: [
    "A borboleta azul dança com os números invisíveis.",
    "Когда картошка поёт, луна плачет.",
    "El gato verde se enamoró de una ecuación matemática.",
    "Quand les spaghettis parlent en ruso, les penguins dansent le tango.",
    "A melancia roxa construiu um castelo feito de geleia.",
    "Den blå flaggen åt min spaghetti og skrev poesia.",
    "Papaya upala kinema sa baguio ng madilim na mundo.",
    "Les nuages jaunes jouent au billard avec les singes roses.",
    "A árvore de sorvete plantou sementes de alegria eletrônica.",
    "Когда мороженое кричит, стулья начинают плясать.",
    "El pingüino noctámbulo jugaba póker con los asteroides.",
    "Quand les chaussettes parlent, les murs écoutent attentivement.",
    "A chuva verde caía para cima com sabor de chiclete cósmico.",
    "Den rosa spöken älskade att lyssna på kakao-musik.",
    "Ang puting mansanas ay umaawit ng mga kanta tungkol sa kultura.",
    "Les bananes transparentes discutaient de la philosophie avec les tomates.",
    "A casa de biscoito tinha janelas feitas de pura loucura.",
    "Когда диван летает, тарелки поют о любви.",
    "Los pájaros de color naranja estudiaban matemáticas en la biblioteca lunar.",
    "Quand le fromage rêve, les murs deviennent des océans.",
    "A pizza dançante era amiga de um robô invisível.",
    "Den gula stolen hade många tankar om galaxer och mjölk.",
    "Ang buhay na lupa ay kumakanta ng mga himig para sa mga aso.",
    "Les horloges violettes se réunissaient chaque mardi pour discuter des rêves.",
    "A vela acesa chorava de felicidade enquanto comia arco-íris.",
    "Когда ночь говорит, день слушает через фиолетовый телефон.",
    "El parque de pesadillas llevaba un sombrero hecho de nubes blandas.",
    "Quand les légumes dansent, les étoiles s'enorgueillissent.",
    "A lampada doce sussurrava segredos para as pedras musicais.",
    "Den svarta snön föll uppåt och sang en kärlekssång för ett osynligt barn."
  ]
};